[2023-11-16T11:47:52.471+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-11-16T11:47:52.500+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-11-16T11:47:52.502+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-16T11:47:52.547+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_docker_compose_task> on 2023-01-02 00:00:00+00:00
[2023-11-16T11:47:52.553+0000] {standard_task_runner.py:57} INFO - Started process 105 to run task
[2023-11-16T11:47:52.563+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Backend_run', 'run_docker_compose_task', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpz8zhgylg']
[2023-11-16T11:47:52.565+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask run_docker_compose_task
[2023-11-16T11:47:52.646+0000] {task_command.py:416} INFO - Running <TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-02T00:00:00+00:00 [running]> on host b631f0e58258
[2023-11-16T11:47:52.867+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Backend_run' AIRFLOW_CTX_TASK_ID='run_docker_compose_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2023-11-16T11:47:52.869+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-16T11:47:52.870+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker-compose -f ./../personal_webapp/docker-compose.yml up -d']
[2023-11-16T11:47:52.889+0000] {subprocess.py:86} INFO - Output:
[2023-11-16T11:47:52.892+0000] {subprocess.py:93} INFO - /bin/bash: line 1: docker-compose: command not found
[2023-11-16T11:47:52.893+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-16T11:47:52.902+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-16T11:47:52.921+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Backend_run, task_id=run_docker_compose_task, execution_date=20230102T000000, start_date=20231116T114752, end_date=20231116T114752
[2023-11-16T11:47:52.994+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task run_docker_compose_task (Bash command failed. The command returned a non-zero exit code 127.; 105)
[2023-11-16T11:47:53.035+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T11:47:53.066+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
